### ISSUE TITLE
Flat module not found - Below errors are seen ! 

### ISSUE THREAD

**Issue by himurali** [samuelkraft/routes#3]
Build Succesful - Execution not fine ! Below errors are seen ! 

npm run dev

> routes@0.1.0 dev /home/murali/ecotourismgit/routes
> next dev

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
ready - started server on http://localhost:3000
error - ./styles/globals.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ref--5-oneOf-6-2!./styles/globals.css)
TypeError: styles.flatMap is not a function

event - build page: /next/dist/pages/_error
wait  - compiling...
error - ./styles/globals.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ref--5-oneOf-6-2!./styles/globals.css)
TypeError: allRules.flat is not a function
{ Error: Cannot find module '/home/murali/ecotourismgit/routes/.next/build-manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at loadComponents (/home/murali/ecotourismgit/routes/node_modules/next/dist/next-server/server/load-components.js:1:1035)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }

**Comment by samuelkraft** [comment]
Replied in email but putting this here for others; Upgrade Node version to fix this issue.

**Comment by himurali** [comment]
Thanks I just did a upgrade of Node to the latest and it worked smoothly !
